#!/usr/bin/env ruby
#
# A simple example showing how to use Einhorn's shared-socket
# features. Einhorn translates the (addr:port[,flags...]) bind spec in
# into a file descriptor number in the EINHORN_FD_# environment
# variables.
#
# Invoke through Einhorn as
#
#     einhorn -b 127.0.0.1:2345,r ./time_server
#
# or, if you want to try out preloading:
#
#     einhorn -b 127.0.0.1:2345,r -p ./time_server ./time_server
require 'rubygems'
require 'einhorn/worker'

def einhorn_main
  puts "Called with ENV['EINHORN_FD_0']: #{ENV['EINHORN_FD_0']}"

  fd_num = Einhorn::Worker.socket!
  socket = Socket.for_fd(fd_num)

  # Came up successfully, so let's set up graceful handler and ACK the
  # master.
  Einhorn::Worker.graceful_shutdown do
    puts "Goodbye from #{$$}"
    exit(0)
  end
  Einhorn::Worker.ack!(:env, true)

  # Real work happens here.
  begin
    while true
      Einhorn::Worker.send_state('listening')
      accepted, _ = socket.accept
      Einhorn::Worker.send_state('working')
      accepted.write("[#{$$}] The current time is: #{Time.now}!\n")
      accepted.close
    end
  rescue Exception => e
    puts e.inspect
  end
end

if $0 == __FILE__
  einhorn_main
end
